### ISSUE TITLE
Human-proof captcha

### ISSUE THREAD

**Issue by fedejinich** [rootstock/faucet#24]
Current captcha it's very difficult, I suggest [this one](https://www.google.com/recaptcha/intro/v3.html) so you don't even need to write any captcha.

**Comment by ida3m0n** [comment]
> Current captcha it's very difficult, I suggest [this one](https://www.google.com/recaptcha/intro/v3.html) so you don't even need to write any captcha.

@fedejinich , this will bring problems to those behind the great firewall. Reason why google´s captcha is not online anymore.
